version: '3.7'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=SocialMedia
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=user
      # You can use whatever password you like
      - MYSQL_PASSWORD=password
      # Password for root access
      - MYSQL_ROOT_PASSWORD=password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      # replace with path to the location you would like the mySQL drive to map to
      - dbData:/var/lib/mysql2
      - ./Database/dump/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

  backend:
      build: '.'
      depends_on:
        - db
      ports:
        # <Port exposed> : inside
        - '8080:8080'

  frontend:
    build: './frontend'
    ports:
      - '80:80'
volumes:
  dbData:
